/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CoupleInfo = IDL.Record({
  'anniversaryDate' : IDL.Text,
  'tagline' : IDL.Text,
  'partner2Name' : IDL.Text,
  'partner1Name' : IDL.Text,
});
export const LoveLetter = IDL.Record({
  'content' : IDL.Text,
  'recipient' : IDL.Text,
  'author' : IDL.Text,
});
export const TimelineMilestone = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getBackgroundMusicKey' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoupleInfo' : IDL.Func([], [CoupleInfo], ['query']),
  'getLoveLetter' : IDL.Func([], [LoveLetter], ['query']),
  'getReasonsList' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTimelineMilestones' : IDL.Func(
      [],
      [IDL.Vec(TimelineMilestone)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBackgroundMusicKey' : IDL.Func([ExternalBlob], [], []),
  'updateCoupleInfo' : IDL.Func([CoupleInfo], [], []),
  'updateLoveLetter' : IDL.Func([LoveLetter], [], []),
  'updateReasonsList' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateTimelineMilestones' : IDL.Func([IDL.Vec(TimelineMilestone)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CoupleInfo = IDL.Record({
    'anniversaryDate' : IDL.Text,
    'tagline' : IDL.Text,
    'partner2Name' : IDL.Text,
    'partner1Name' : IDL.Text,
  });
  const LoveLetter = IDL.Record({
    'content' : IDL.Text,
    'recipient' : IDL.Text,
    'author' : IDL.Text,
  });
  const TimelineMilestone = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getBackgroundMusicKey' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoupleInfo' : IDL.Func([], [CoupleInfo], ['query']),
    'getLoveLetter' : IDL.Func([], [LoveLetter], ['query']),
    'getReasonsList' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getTimelineMilestones' : IDL.Func(
        [],
        [IDL.Vec(TimelineMilestone)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBackgroundMusicKey' : IDL.Func([ExternalBlob], [], []),
    'updateCoupleInfo' : IDL.Func([CoupleInfo], [], []),
    'updateLoveLetter' : IDL.Func([LoveLetter], [], []),
    'updateReasonsList' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateTimelineMilestones' : IDL.Func([IDL.Vec(TimelineMilestone)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };