/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CoupleInfo = IDL.Record({
  'anniversaryDate' : IDL.Text,
  'tagline' : IDL.Text,
  'partner2Name' : IDL.Text,
  'partner1Name' : IDL.Text,
});
export const LoveLetter = IDL.Record({
  'content' : IDL.Text,
  'recipient' : IDL.Text,
  'author' : IDL.Text,
});
export const TimelineMilestone = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'getCoupleInfo' : IDL.Func([], [CoupleInfo], ['query']),
  'getLoveLetter' : IDL.Func([], [LoveLetter], ['query']),
  'getReasonsList' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTimelineMilestones' : IDL.Func(
      [],
      [IDL.Vec(TimelineMilestone)],
      ['query'],
    ),
  'updateCoupleInfo' : IDL.Func([CoupleInfo], [], []),
  'updateLoveLetter' : IDL.Func([LoveLetter], [], []),
  'updateReasonsList' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateTimelineMilestones' : IDL.Func([IDL.Vec(TimelineMilestone)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CoupleInfo = IDL.Record({
    'anniversaryDate' : IDL.Text,
    'tagline' : IDL.Text,
    'partner2Name' : IDL.Text,
    'partner1Name' : IDL.Text,
  });
  const LoveLetter = IDL.Record({
    'content' : IDL.Text,
    'recipient' : IDL.Text,
    'author' : IDL.Text,
  });
  const TimelineMilestone = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'getCoupleInfo' : IDL.Func([], [CoupleInfo], ['query']),
    'getLoveLetter' : IDL.Func([], [LoveLetter], ['query']),
    'getReasonsList' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getTimelineMilestones' : IDL.Func(
        [],
        [IDL.Vec(TimelineMilestone)],
        ['query'],
      ),
    'updateCoupleInfo' : IDL.Func([CoupleInfo], [], []),
    'updateLoveLetter' : IDL.Func([LoveLetter], [], []),
    'updateReasonsList' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateTimelineMilestones' : IDL.Func([IDL.Vec(TimelineMilestone)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };